# Generated by Django 4.0 on 2022-06-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('fat', models.DecimalField(decimal_places=1, max_digits=4)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=4)),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diet.food')),
            ],
        ),
    ]
