# Generated by Django 4.0 on 2022-06-12 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("diet", "0002_consumedfood_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
            preserve_default=False,
        ),
    ]
