# Generated by Django 4.0 on 2022-06-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('diet', '0003_food_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='food',
            unique_together={('name', 'user')},
        ),
    ]
