# Generated by Django 4.0 on 2022-06-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0004_alter_food_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumedfood",
            name="servings",
            field=models.IntegerField(default=1),
        ),
    ]
