# Generated by Django 4.0 on 2022-06-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_consumedfood_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumedfood',
            name='servings',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
