# Generated by Django 4.0 on 2021-12-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('exercise', '0003_alter_session_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Workout',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='session',
            new_name='workout',
        ),
    ]
