# Generated by Django 4.0 on 2021-12-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_stravaaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stravaaccount',
            old_name='user_name',
            new_name='username',
        ),
    ]
