# Generated by Django 4.0 on 2021-12-28 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('exercise', '0006_rename_user_name_stravaaccount_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moving_time', models.IntegerField()),
                ('elapsed_time', models.IntegerField()),
                ('total_elevation_gain', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=100)),
                ('workout_type', models.IntegerField()),
                ('strava_id', models.IntegerField()),
                ('external_id', models.TextField()),
                ('upload_id', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('start_date_local', models.DateTimeField()),
                ('timezone', models.CharField(max_length=100)),
                ('utc_offset', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_speed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_speed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_heartrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_heartrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('elev_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('elev_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suffer_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_seesions', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.TextField()),
                ('summary_polyline', models.TextField()),
                ('resource_state', models.IntegerField()),
                ('cardio_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='exercise.cardiosession')),
            ],
        ),
    ]
