# Generated by Django 4.0 on 2021-12-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0009_cardiosession_has_heartrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardiosession",
            name="suffer_score",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
