# Generated by Django 4.0 on 2021-12-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_alter_cardiosession_suffer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiosession',
            name='workout_type',
            field=models.IntegerField(null=True),
        ),
    ]
