# Generated by Django 4.0 on 2021-12-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_alter_cardiosession_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiosession',
            name='external_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
