# Generated by Django 4.0 on 2021-12-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0012_alter_cardiosession_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiosession',
            name='upload_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
