# Generated by Django 4.0 on 2022-01-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0015_alter_map_resource_state_alter_map_summary_polyline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="cardio_session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maps",
                to="exercise.cardiosession",
            ),
        ),
    ]
