# Generated by Django 4.0 on 2022-01-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_alter_map_cardio_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='cardio_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='exercise.cardiosession'),
        ),
    ]
