# Generated by Django 4.0 on 2022-01-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0017_alter_map_cardio_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardiosession",
            name="end_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cardiosession",
            name="end_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cardiosession",
            name="start_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cardiosession",
            name="start_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
