# Generated by Django 4.0.6 on 2022-09-04 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shopping", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="ItemInstance",
        ),
    ]
