# Generated by Django 4.0.6 on 2022-09-04 20:40

from django.db import migrations, models
import django.db.models.deletion
import shopping.models


def forwards_func(apps, schema_editor):
    Item = apps.get_model("shopping", "Item")
    ItemInstance = apps.get_model("shopping", "ItemInstance")

    for instance in ItemInstance.objects.all():
        item = Item.objects.get_or_create(name=instance.name.strip().lower())[0]
        instance.item = item
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0003_rename_item_iteminstance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("photo", models.ImageField(upload_to=shopping.models.upload_to)),
            ],
        ),
        migrations.AddField(
            model_name="iteminstance",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shopping.item",
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
