name: Testing
on: push

env:
  SECRET_KEY: secret_key
  DEBUG: False
  ENVIRONMENT: test
  SITE_URL: http://localhost:8000
  STRAVA_CLIENT_ID: foo
  STRAVA_CLIENT_SECRET: bar
  STRAVA_WEBHOOK_VERIFY_TOKEN: baz
  AWS_ACCESS_KEY: asdf
  AWS_SECRET_ACCESS_KEY: asdf
  AWS_ACCESS_KEY_ID: asdf


jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user -r requirements.txt
        python3 manage.py test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
